### ISSUE TITLE
create main readme

### ISSUE THREAD

**Issue by brauliodiez** [Lemoncode/redux-sagas-typescript-by-example#1]

**Comment by dailymp** [comment]
Hello @brauliodiez, this is for me?

**Comment by brauliodiez** [comment]
Yups, go through each sample, then create a global readme indicating the goal of this repo and a short description of each of the samples.

Did you accept the invitation?

**Comment by dailymp** [comment]
Ok, @brauliodiez. I will put my hands on it!
